### ISSUE TITLE
The ACU responds with an error when commanding a receiver setup and the telescope is already unstowed

### ISSUE THREAD

**Issue by flyingfrog81** [discos/discos#23]
Originally reported by @aorlati
Date Submitted: 2013-05-24
Category: ticket
OS: 
OS Version: 
Platform: 
Priority: normal
Product Version: NURAGHE-0.1
Project: Nuraghe
Reproducibility: always
Resolution: open
Severity: minor
Status: new
Updated: 2016-01-14
[Link to original mantis issue #0000094](http://www.med.ira.inaf.it/mantisbt/view.php?id=0000094)

**Comment by giuseppe-carboni** [comment]
I have no access to the original mantis issue due to lack of login credentials, but my guess is that a receiversSetup never actually ask DISCOS to communicate with the Antenna Control Unit (at least not in the current DISCOS version). My guess is that this is not relevant anymore or it has been previously fixed without mentioning this issue.

**Comment by aorlati** [comment]
I agree, shall we close the issue?

**Comment by giuseppe-carboni** [comment]
Yep. Closing.
