### ISSUE TITLE
'project' command on the operatorInput could return a message to the user

### ISSUE THREAD

**Issue by giuseppe-carboni** [discos/discos#539]
It could be a good idea to print to the user a message containing a link/useful information about the state of the system/telescope.

**Comment by aorlati** [comment]
expanded parser in order to support string as return value. 
Now we should code the project command so that a well come message is  retrieved from CDB.
An had hoc DB entry should be created in DataBlock/.
Also I've set the checkProjectCode in Scheduler configuration to true. I can't see any reason to keep it false.

**Comment by aorlati** [comment]
@giuseppe-carboni did you check the branch? Are you going to complete the coding required to close the issue.

**Comment by giuseppe-carboni** [comment]
Yes, I'm working on it and I will push some code soon
